//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMW.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValuesOfWellDiameters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValuesOfWellDiameters() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VMW.Resources.ValuesOfWellDiameters", typeof(ValuesOfWellDiameters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ~Diameters
        ///73;59
        ///73;62
        ///88.9;76
        ///100;80
        ///101.6;88.6
        ///114.3;100.3
        ///114.3;96.3
        ///114.3;98.3
        ///114.3;100.3
        ///114.3;102.3
        ///127;109
        ///127;111
        ///127;113
        ///127;115
        ///139.7;117.7
        ///139.7;119.7
        ///139.7;121.7
        ///139.7;123.7
        ///139.7;125.7
        ///139.7;127.7
        ///146;124
        ///146;126
        ///146;128
        ///146;130
        ///146;132
        ///146;133
        ///168;140.3
        ///168;144.3
        ///168;146.3
        ///168;148.3
        ///168;150.3
        ///168.3;140.3
        ///168.3;144.3
        ///168.3;146.3
        ///168.3;148.3
        ///168.3;150.3
        ///168.3;152.3
        ///168.3;154.3
        ///168.3;155.3
        ///177.8;149.8
        ///177.8;153.8
        ///177.8;155.8
        ///177.8;157.8
        ///177.8;159.8
        ///17 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Diameters {
            get {
                return ResourceManager.GetString("Diameters", resourceCulture);
            }
        }
    }
}
